// Alert model — stores security alerts generated by the decision engine
const mongoose = require('mongoose');

const AlertSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    loginEventId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'LoginEvent',
    },
    severity: {
      type: String,
      enum: ['info', 'warning', 'critical'],
      default: 'info',
    },
    message: { type: String, required: true },
    action: { type: String },   // what auto-healing action was taken
    resolved: { type: Boolean, default: false },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Alert', AlertSchema);
